/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type BackupLocation = "Local" | "Remote";
/**
 * 回應類型枚舉
 */
export type ResponseType = "Ok" | "Err" | "Unspecified";
/**
 * 月份枚舉
 */
export type Month = "Jan" | "Feb" | "Mar" | "Apr" | "May" | "Jun" | "Jul" | "Aug" | "Sep" | "Oct" | "Nov" | "Dec";
/**
 * 星期枚舉
 */
export type Week = "Mon" | "Tue" | "Wed" | "Thu" | "Fri" | "Sat" | "Sun";
export type ReductionRequest =
  | {
      Type: "Remote";
      name: string;
    }
  | {
      Type: "Local";
      file: string;
    };
export type DePatchVxlanid =
  | {
      groupname: string;
    }
  | {
      pcs: string[];
    };
/**
 * 狀態枚舉
 */
export type Status = "Active" | "Stopped" | "Uninstalled";
/**
 * 日志等级
 */
export type Level = "debug" | "info" | "notice" | "warn" | "error" | "crit" | "alert" | "emerg";

/**
 * 所有的 JSON Schema 集合
 */
export interface AllSchemas {
  Auth: AuthSchemas;
  ChmBackup: ChmBackupSchemas;
  ChmMca: ChmMcaSchemas;
  ChmPcManager: ChmPcManagerSchemas;
  Common: CommonSchemas;
  Login: LoginSchemas;
}
/**
 * auth.rs相關的 JSON Schema
 */
export interface AuthSchemas {
  AuthUser: AuthUser;
}
/**
 * 認證使用者資訊
 */
export interface AuthUser {
  Role?: string | null;
  Uid: string;
  Username?: string | null;
}
/**
 * handles/chm/backup 相關的 JSON Schema
 */
export interface ChmBackupSchemas {
  BackupRequest: BackupRequest;
  BackupResponse: BackupResponse;
  GetBackupsRequest: GetBackupsRequest;
  GetBackupsResponse: GetBackupsResponse;
  ReductionRequest: ReductionRequest;
}
export interface BackupRequest {
  Name: string;
  Type: BackupLocation;
}
/**
 * 回應結果結構體
 */
export interface BackupResponse {
  DownloadUrl?: string | null;
  Id?: string | null;
  Message: string;
  Type: ResponseType;
}
export interface GetBackupsRequest {
  Limit?: number;
}
export interface GetBackupsResponse {
  Backups: InnerGetBackupResponse[];
  Length: number;
}
/**
 * 日期结构体
 */
export interface InnerGetBackupResponse {
  Day: number;
  Month: Month;
  Name: string;
  Time: Time;
  Week: Week;
  Year: number;
}
/**
 * 時間結構體
 */
export interface Time {
  Hour: number;
  Min: number;
}
/**
 * handles/chm/mca 相關的 JSON Schema
 */
export interface ChmMcaSchemas {
  GetRevokeds: GetRevokeds;
  GetValids: GetValids;
  RevokeRequest: RevokeRequest;
  Revoked: Revoked;
  Valid: Valid;
}
/**
 * 憑證吊銷清單
 */
export interface GetRevokeds {
  Length: number;
  Revoke: Revoked[];
}
/**
 * 憑證吊銷清單(個體)
 */
export interface Revoked {
  Number: string;
  Reason: string;
  Time: string;
}
/**
 * 憑證有效清單
 */
export interface GetValids {
  Length: number;
  Valid: Valid[];
}
/**
 * 憑證有效清單(個體)
 */
export interface Valid {
  Name: string;
  Period: string;
  Signer: string;
}
/**
 * 憑證吊銷請求
 */
export interface RevokeRequest {
  Name: string;
  Reason: string;
}
/**
 * handles/chm/pc_manager 相關的 JSON Schema
 */
export interface ChmPcManagerSchemas {
  DePatchVxlanId: DePatchVxlanid;
  DePutVxlanId: DePutVxlanid;
  DeletePcGroupRequest: DeletePcGroupRequest;
  DeletePcRequest: DeletePcRequest;
  DeletePcResponse: DeletePcResponse;
  GetPcGroupResponseResult: GetPcgroupResponseResult;
  PatchPcGroupRequest: PatchPcgroupRequest;
  PcInfo: PcInformation;
  PcManagerRequest: PCManagerRequest;
  PostPcGroupRequest: PostPcgroupRequest;
  PutPcGroupRequest: PutPcgroupRequest;
  RebootPcResponse: RebootPcResponse;
  ShutdownPcResponse: ShutdownPcResponse;
  SpectificRequest: SpecificRequest;
  Uuid: Uuid;
  UuidsRequest: UuidsRequest;
  VxlanId: Vxlanid;
}
export interface DePutVxlanid {
  Groupname: string;
  Pcs: string[];
}
export interface DeletePcGroupRequest {
  Vxlanid: number;
}
export interface DeletePcRequest {
  Passwords: string[];
  Uuids: string[];
}
export interface DeletePcResponse {
  Length: number;
  Pcs: {
    [k: string]: ResponseResult;
  };
}
/**
 * 回應結果結構體
 */
export interface ResponseResult {
  Message: string;
  Type: ResponseType;
}
export interface GetPcgroupResponseResult {
  Groups: {
    [k: string]: Vxlanid;
  };
  Length: number;
}
export interface Vxlanid {
  Groupname: string;
  Pcs: string[];
}
export interface PatchPcgroupRequest {}
export interface PcInformation {
  Length: number;
  Pcs: {
    [k: string]: Uuid;
  };
}
export interface Uuid {
  Hostname: string;
  Ip: string;
  Status: boolean;
}
export interface PCManagerRequest {
  Ip: string;
  Password: string;
}
export interface PostPcgroupRequest {
  Cidr: string;
  Groupname: string;
}
export interface PutPcgroupRequest {}
export interface RebootPcResponse {
  Length: number;
  Pcs: {
    [k: string]: ResponseResult;
  };
}
export interface ShutdownPcResponse {
  Length: number;
  Pcs: {
    [k: string]: ResponseResult;
  };
}
export interface SpecificRequest {
  Uuid: string[];
}
export interface UuidsRequest {
  Uuids: string[];
}
/**
 * commons 相關的 JSON Schema
 */
export interface CommonSchemas {
  CommonInfo: CommonInfo;
  Date: Date;
  ErrorLog: ErrorLog;
  Level: Level;
  Month: Month;
  ResponseResult: ResponseResult;
  ResponseType: ResponseType;
  Status: Status;
  Time: Time;
  UuidRequest: UuidRequest;
  Week: Week;
}
/**
 * 通用信息結構體
 */
export interface CommonInfo {
  Cpu: number;
  Hostname: string;
  Ip?: string | null;
  Memory: number;
  Status: Status;
}
/**
 * 日期结构体
 */
export interface Date {
  Day: number;
  Month: Month;
  Time: Time;
  Week: Week;
  Year: number;
}
/**
 * 錯誤日志结构体
 */
export interface ErrorLog {
  Client: string;
  Date: Date;
  Level: Level;
  Message: string;
  Module: string;
  Pid: number;
}
/**
 * 帶 UUID 的請求結構體
 */
export interface UuidRequest {
  Uuid: string;
}
/**
 * handles/login 相關的 JSON Schema
 */
export interface LoginSchemas {
  LoginRequest: LoginRequest;
}
/**
 * 登入請求
 */
export interface LoginRequest {
  Password: string;
  Username: string;
}
