// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ActionRestartData, ActionRestartResponses, ActionStartData, ActionStartResponses, ActionStopData, ActionStopResponses, AddPcData, AddPcErrors, AddPcResponses, DeleteGroupData, DeleteGroupResponses, DeletePcData, DeletePcErrors, DeletePcgroupData, DeletePcgroupErrors, DeletePcgroupResponses, DeletePcResponses, DeleteUserData, DeleteUserResponses, GetAllPcData, GetAllPcErrors, GetAllPcResponses, GetApacheAllData, GetApacheAllResponses, GetBackupRootData, GetBackupRootResponses, GetGroupData, GetGroupResponses, GetInfoAllData, GetInfoAllErrors, GetInfoAllResponses, GetPcgroupData, GetPcgroupErrors, GetPcgroupResponses, GetSpecificPcData, GetSpecificPcErrors, GetSpecificPcResponses, GetUserData, GetUserResponses, LoginData, LoginErrors, LoginResponses, LogoutData, LogoutErrors, LogoutResponses, MeData, MeErrors, MeResponses, PatchGroupData, PatchGroupResponses, PatchPcgroupData, PatchPcgroupErrors, PatchPcgroupResponses, PatchUserData, PatchUserResponses, PostBackupRootData, PostBackupRootResponses, PostGroupData, PostGroupResponses, PostInfoGetData, PostInfoGetErrors, PostInfoGetResponses, PostPcgroupData, PostPcgroupErrors, PostPcgroupResponses, PostReductionData, PostReductionResponses, PostUserData, PostUserResponses, PutGroupData, PutGroupResponses, PutPcgroupData, PutPcgroupErrors, PutPcgroupResponses, PutUserData, PutUserResponses, RebootPcData, RebootPcErrors, RebootPcResponses, RevokeData, RevokedData, RevokedErrors, RevokedResponses, RevokeErrors, RevokeResponses, ShutdownPcData, ShutdownPcErrors, ShutdownPcResponses, ValidData, ValidErrors, ValidResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getBackupRoot = <ThrowOnError extends boolean = false>(options: Options<GetBackupRootData, ThrowOnError>) => (options.client ?? client).get<GetBackupRootResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/chm/backup',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postBackupRoot = <ThrowOnError extends boolean = false>(options: Options<PostBackupRootData, ThrowOnError>) => (options.client ?? client).post<PostBackupRootResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/chm/backup',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postReduction = <ThrowOnError extends boolean = false>(options: Options<PostReductionData, ThrowOnError>) => (options.client ?? client).post<PostReductionResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/chm/backup/reduction',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * DELETE /api/chm/group
 */
export const deleteGroup = <ThrowOnError extends boolean = false>(options: Options<DeleteGroupData, ThrowOnError>) => (options.client ?? client).delete<DeleteGroupResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/chm/group',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * GET /api/chm/group
 */
export const getGroup = <ThrowOnError extends boolean = false>(options?: Options<GetGroupData, ThrowOnError>) => (options?.client ?? client).get<GetGroupResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/chm/group',
    ...options
});

/**
 * PATCH /api/chm/group
 */
export const patchGroup = <ThrowOnError extends boolean = false>(options: Options<PatchGroupData, ThrowOnError>) => (options.client ?? client).patch<PatchGroupResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/chm/group',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * POST /api/chm/group
 */
export const postGroup = <ThrowOnError extends boolean = false>(options: Options<PostGroupData, ThrowOnError>) => (options.client ?? client).post<PostGroupResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/chm/group',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * PUT /api/chm/group
 */
export const putGroup = <ThrowOnError extends boolean = false>(options: Options<PutGroupData, ThrowOnError>) => (options.client ?? client).put<PutGroupResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/chm/group',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const revoke = <ThrowOnError extends boolean = false>(options: Options<RevokeData, ThrowOnError>) => (options.client ?? client).post<RevokeResponses, RevokeErrors, ThrowOnError>({
    responseType: 'json',
    url: '/chm/mCA/revoke',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const revoked = <ThrowOnError extends boolean = false>(options?: Options<RevokedData, ThrowOnError>) => (options?.client ?? client).get<RevokedResponses, RevokedErrors, ThrowOnError>({
    responseType: 'json',
    url: '/chm/mCA/revoked',
    ...options
});

export const valid = <ThrowOnError extends boolean = false>(options?: Options<ValidData, ThrowOnError>) => (options?.client ?? client).get<ValidResponses, ValidErrors, ThrowOnError>({
    responseType: 'json',
    url: '/chm/mCA/valid',
    ...options
});

export const deletePc = <ThrowOnError extends boolean = false>(options: Options<DeletePcData, ThrowOnError>) => (options.client ?? client).delete<DeletePcResponses, DeletePcErrors, ThrowOnError>({
    responseType: 'json',
    url: '/chm/pc',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const addPc = <ThrowOnError extends boolean = false>(options: Options<AddPcData, ThrowOnError>) => (options.client ?? client).post<AddPcResponses, AddPcErrors, ThrowOnError>({
    responseType: 'json',
    url: '/chm/pc/add',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getAllPc = <ThrowOnError extends boolean = false>(options?: Options<GetAllPcData, ThrowOnError>) => (options?.client ?? client).get<GetAllPcResponses, GetAllPcErrors, ThrowOnError>({
    responseType: 'json',
    url: '/chm/pc/all',
    ...options
});

export const rebootPc = <ThrowOnError extends boolean = false>(options: Options<RebootPcData, ThrowOnError>) => (options.client ?? client).post<RebootPcResponses, RebootPcErrors, ThrowOnError>({
    responseType: 'json',
    url: '/chm/pc/reboot',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const shutdownPc = <ThrowOnError extends boolean = false>(options: Options<ShutdownPcData, ThrowOnError>) => (options.client ?? client).post<ShutdownPcResponses, ShutdownPcErrors, ThrowOnError>({
    responseType: 'json',
    url: '/chm/pc/shutdown',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getSpecificPc = <ThrowOnError extends boolean = false>(options: Options<GetSpecificPcData, ThrowOnError>) => (options.client ?? client).get<GetSpecificPcResponses, GetSpecificPcErrors, ThrowOnError>({
    responseType: 'json',
    url: '/chm/pc/specific',
    ...options
});

export const deletePcgroup = <ThrowOnError extends boolean = false>(options: Options<DeletePcgroupData, ThrowOnError>) => (options.client ?? client).delete<DeletePcgroupResponses, DeletePcgroupErrors, ThrowOnError>({
    responseType: 'json',
    url: '/chm/pcgroup',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getPcgroup = <ThrowOnError extends boolean = false>(options?: Options<GetPcgroupData, ThrowOnError>) => (options?.client ?? client).get<GetPcgroupResponses, GetPcgroupErrors, ThrowOnError>({
    responseType: 'json',
    url: '/chm/pcgroup',
    ...options
});

export const patchPcgroup = <ThrowOnError extends boolean = false>(options: Options<PatchPcgroupData, ThrowOnError>) => (options.client ?? client).patch<PatchPcgroupResponses, PatchPcgroupErrors, ThrowOnError>({
    responseType: 'json',
    url: '/chm/pcgroup',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postPcgroup = <ThrowOnError extends boolean = false>(options: Options<PostPcgroupData, ThrowOnError>) => (options.client ?? client).post<PostPcgroupResponses, PostPcgroupErrors, ThrowOnError>({
    responseType: 'json',
    url: '/chm/pcgroup',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const putPcgroup = <ThrowOnError extends boolean = false>(options: Options<PutPcgroupData, ThrowOnError>) => (options.client ?? client).put<PutPcgroupResponses, PutPcgroupErrors, ThrowOnError>({
    responseType: 'json',
    url: '/chm/pcgroup',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * DELETE /api/chm/user
 */
export const deleteUser = <ThrowOnError extends boolean = false>(options: Options<DeleteUserData, ThrowOnError>) => (options.client ?? client).delete<DeleteUserResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/chm/user',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * GET /api/chm/user
 */
export const getUser = <ThrowOnError extends boolean = false>(options?: Options<GetUserData, ThrowOnError>) => (options?.client ?? client).get<GetUserResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/chm/user',
    ...options
});

/**
 * PATCH /api/chm/user  （單一內容）
 */
export const patchUser = <ThrowOnError extends boolean = false>(options: Options<PatchUserData, ThrowOnError>) => (options.client ?? client).patch<PatchUserResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/chm/user',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * POST /api/chm/user
 */
export const postUser = <ThrowOnError extends boolean = false>(options: Options<PostUserData, ThrowOnError>) => (options.client ?? client).post<PostUserResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/chm/user',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * PUT /api/chm/user  （整筆）
 */
export const putUser = <ThrowOnError extends boolean = false>(options: Options<PutUserData, ThrowOnError>) => (options.client ?? client).put<PutUserResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/chm/user',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * POST /api/info/get
 */
export const postInfoGet = <ThrowOnError extends boolean = false>(options: Options<PostInfoGetData, ThrowOnError>) => (options.client ?? client).post<PostInfoGetResponses, PostInfoGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/info/get',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * GET /api/info/getAll
 */
export const getInfoAll = <ThrowOnError extends boolean = false>(options?: Options<GetInfoAllData, ThrowOnError>) => (options?.client ?? client).get<GetInfoAllResponses, GetInfoAllErrors, ThrowOnError>({
    responseType: 'json',
    url: '/info/getAll',
    ...options
});

export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    responseType: 'json',
    url: '/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const me = <ThrowOnError extends boolean = false>(options?: Options<MeData, ThrowOnError>) => (options?.client ?? client).get<MeResponses, MeErrors, ThrowOnError>({
    responseType: 'json',
    url: '/login/me',
    ...options
});

export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>) => (options?.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>({
    responseType: 'json',
    url: '/logout',
    ...options
});

export const getApacheAll = <ThrowOnError extends boolean = false>(options: Options<GetApacheAllData, ThrowOnError>) => (options.client ?? client).get<GetApacheAllResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/server/apache',
    ...options
});

export const actionRestart = <ThrowOnError extends boolean = false>(options: Options<ActionRestartData, ThrowOnError>) => (options.client ?? client).post<ActionRestartResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/server/apache/action/restart',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const actionStart = <ThrowOnError extends boolean = false>(options: Options<ActionStartData, ThrowOnError>) => (options.client ?? client).post<ActionStartResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/server/apache/action/start',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const actionStop = <ThrowOnError extends boolean = false>(options: Options<ActionStopData, ThrowOnError>) => (options.client ?? client).post<ActionStopResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/server/apache/action/stop',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
