// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}/api` | (string & {});
};

export type AccessLog = {
    Byte: number;
    Date: _Date;
    Ip: string;
    Method: string;
    Protocol: string;
    Referer: string;
    Status: number;
    Url: string;
    UserAgent: string;
};

export type ApacheResponse = CommonInfo & {
    Connections: number;
    Logs: Logs;
};

/**
 * 認證使用者資訊
 */
export type AuthUser = {
    Role?: string | null;
    Uid: string;
    Username?: string | null;
};

export type BackupLocation = 'Local' | 'Remote';

export type BackupRequest = {
    Name: string;
    Type: BackupLocation;
};

export type BackupResponse = ResponseResult & {
    DownloadUrl?: string | null;
    Id?: string | null;
};

export type ClusterSummary = {
    Cpu: number;
    Disk: number;
    Memory: number;
};

/**
 * 通用信息結構體
 */
export type CommonInfo = {
    Cpu: number;
    Hostname: string;
    Ip?: string | null;
    Memory: number;
    Status: Status;
};

export type CreateGroupRequest = {
    Groupname: string;
    Users: Array<string>;
};

export type CreateUserRequest = {
    Cn: string;
    DisplayName: string;
    Gecos: string;
    GivenName: string;
    Group: Array<string>;
    HomeDirectory: string;
    Password: string;
    Shell: string;
    Sn: string;
    Username: string;
};

/**
 * 日期结构体
 */
export type _Date = {
    Day: number;
    Month: Month;
    Time: Time;
    Week: Week;
    Year: number;
};

export type DePatchVxlanid = {
    Groupname: {
        groupname: string;
    };
} | {
    Pcs: {
        pcs: Array<string>;
    };
};

export type DePutVxlanid = {
    Groupname: string;
    Pcs: Array<string>;
};

export type DeleteGroupRequest = {
    Gid: string;
};

export type DeletePcGroupRequest = {
    Vxlanid: number;
};

export type DeletePcRequest = {
    Passwords: Array<string>;
    Uuids: Array<string>;
};

export type DeletePcResponse = {
    Length: number;
    Pcs: {
        [key: string]: ResponseResult;
    };
};

export type DeleteUserRequest = {
    Uid: string;
};

/**
 * 錯誤日志结构体
 */
export type ErrorLog = {
    Client: string;
    Date: _Date;
    Level: Level;
    Message: string;
    Module: string;
    Pid: number;
};

export type GetAllInfoResponse = {
    Cluster: ClusterSummary;
    Info: InfoCounts;
};

export type GetBackupsRequest = {
    Limit?: number;
};

export type GetBackupsResponse = {
    Backups: Array<InnerGetBackupResponse>;
    Length: number;
};

export type GetPcgroupResponseResult = {
    Groups: {
        [key: string]: Vxlanid;
    };
    Length: number;
};

export type GetUserEntry = {
    Cn: string;
    DisplayName: string;
    Gecos: string;
    GidNumber: string;
    GivenName: string;
    Group: Array<string>;
    HomeDirectory: string;
    Shell: string;
    Sn: string;
    Username: string;
};

export type GroupEntry = {
    Groupname: string;
    Users?: Array<string>;
};

export type GroupsCollection = {
    Groups: {
        [key: string]: GroupEntry;
    };
};

export type InfoCounts = {
    Dang: number;
    Safe: number;
    Warn: number;
};

/**
 * POST /api/info/get
 */
export type InfoGetRequest = {
    Target?: null | Target;
    /**
     * None 代表全部；Some(uuid) 代表指定主機
     */
    Uuid?: string | null;
};

export type InfoGetResponse = {
    Length: number;
    Pcs: {
        [key: string]: PcMetrics;
    };
};

export type InnerGetBackupResponse = _Date & {
    Name: string;
};

/**
 * 日志等级
 */
export type Level = 'debug' | 'info' | 'notice' | 'warn' | 'error' | 'crit' | 'alert' | 'emerg';

/**
 * 登入請求
 */
export type LoginRequest = {
    Password: string;
    Username: string;
};

export type Logs = {
    AccessLog: Array<AccessLog>;
    Acclength: number;
    Errlength: number;
    ErrorLog: Array<ErrorLog>;
};

/**
 * 月份枚舉
 */
export type Month = 'Jan' | 'Feb' | 'Mar' | 'Apr' | 'May' | 'Jun' | 'Jul' | 'Aug' | 'Sep' | 'Oct' | 'Nov' | 'Dec';

export type PcManagerRequest = {
    Ip: string;
    Password: string;
};

export type PatchGroupEntry = {
    Groupname?: string | null;
    Users?: Array<string> | null;
};

export type PatchGroupsRequest = {
    [key: string]: PatchGroupEntry;
};

export type PatchPcgroupRequest = {
    [key: string]: DePatchVxlanid;
};

export type PatchUserEntry = {
    Cn?: string | null;
    DisplayName?: string | null;
    Gecos?: string | null;
    GivenName?: string | null;
    Group?: Array<string> | null;
    HomeDirectory?: string | null;
    Password?: string | null;
    Shell?: string | null;
    Sn?: string | null;
};

export type PatchUsersRequest = {
    [key: string]: PatchUserEntry;
};

export type PcInformation = {
    Length: number;
    Pcs: {
        [key: string]: Uuid;
    };
};

export type PcMetrics = {
    Cpu: number;
    CpuStatus: StatusLabel;
    Disk: number;
    DiskStatus: StatusLabel;
    MemStatus: StatusLabel;
    Memory: number;
};

export type Pcs = {
    Installed: {
        [key: string]: CommonInfo;
    };
} | {
    NotInstalled: {
        [key: string]: string;
    };
};

export type PostPcgroupRequest = {
    Cidr: string;
    Groupname: string;
};

export type PutGroupsRequest = {
    [key: string]: GroupEntry;
};

export type PutPcgroupRequest = {
    [key: string]: DePutVxlanid;
};

export type PutUserEntry = {
    Cn: string;
    DisplayName: string;
    Gecos: string;
    GivenName: string;
    Group: Array<string>;
    HomeDirectory: string;
    Password: string;
    Shell: string;
    Sn: string;
};

export type PutUsersRequest = {
    [key: string]: never;
};

export type RebootPcResponse = {
    Length: number;
    Pcs: {
        [key: string]: ResponseResult;
    };
};

export type ReductionRequest = {
    Type: 'Remote';
    name: string;
} | {
    Type: 'Local';
    file: string;
};

/**
 * 回應結果結構體
 */
export type ResponseResult = {
    Message: string;
    Type: ResponseType;
};

/**
 * 回應類型枚舉
 */
export type ResponseType = 'Ok' | 'Err' | 'Unspecified';

/**
 * 憑證吊銷請求
 */
export type RevokeRequest = {
    Name: string;
    Reason: string;
};

/**
 * 憑證吊銷清單(個體)
 */
export type Revoked = {
    Number: string;
    Reason: string;
    Time: string;
};

export type ShutdownPcResponse = {
    Length: number;
    Pcs: {
        [key: string]: ResponseResult;
    };
};

/**
 * 狀態枚舉
 */
export type Status = 'Active' | 'Stopped' | 'Uninstalled';

export type StatusLabel = 'Safe' | 'Warn' | 'Dang' | 'Unknown';

export type Target = 'Safe' | 'Warn' | 'Dang';

/**
 * 時間結構體
 */
export type Time = {
    Hour: number;
    Min: number;
};

export type UsersCollection = {
    Length: number;
    Users: {
        [key: string]: GetUserEntry;
    };
};

export type Uuid = {
    Hostname: string;
    Ip: string;
    Status: boolean;
};

/**
 * 帶 UUID 的請求結構體
 */
export type UuidRequest = {
    Uuid: string;
};

export type UuidsRequest = {
    Uuids: Array<string>;
};

/**
 * 憑證有效清單(個體)
 */
export type Valid = {
    Name: string;
    Period: string;
    Signer: string;
};

export type Vxlanid = {
    Groupname: string;
    Pcs: Array<string>;
};

/**
 * 星期枚舉
 */
export type Week = 'Mon' | 'Tue' | 'Wed' | 'Thu' | 'Fri' | 'Sat' | 'Sun';

/**
 * 憑證吊銷清單
 */
export type GetRevokeds = {
    Length: number;
    Revoke: Array<Revoked>;
};

/**
 * 憑證有效清單
 */
export type GetValids = {
    Length: number;
    Valid: Array<Valid>;
};

export type StallRequest = {
    Server: string;
    Uuids: Array<string>;
};

export type StalledResponse = {
    Length: number;
    Pcs: Pcs;
};

export type StalledRequest = {
    Server: string;
};

export type GetBackupRootData = {
    body: GetBackupsRequest;
    path?: never;
    query?: never;
    url: '/chm/backup';
};

export type GetBackupRootResponses = {
    200: GetBackupsResponse;
};

export type GetBackupRootResponse = GetBackupRootResponses[keyof GetBackupRootResponses];

export type PostBackupRootData = {
    body: BackupRequest;
    path?: never;
    query?: never;
    url: '/chm/backup';
};

export type PostBackupRootResponses = {
    200: BackupResponse;
};

export type PostBackupRootResponse = PostBackupRootResponses[keyof PostBackupRootResponses];

export type PostReductionData = {
    body: ReductionRequest;
    path?: never;
    query?: never;
    url: '/chm/backup/reduction';
};

export type PostReductionResponses = {
    200: ResponseResult;
};

export type PostReductionResponse = PostReductionResponses[keyof PostReductionResponses];

export type DeleteGroupData = {
    body: DeleteGroupRequest;
    path?: never;
    query?: never;
    url: '/chm/group';
};

export type DeleteGroupResponses = {
    200: ResponseResult;
};

export type DeleteGroupResponse = DeleteGroupResponses[keyof DeleteGroupResponses];

export type GetGroupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/chm/group';
};

export type GetGroupResponses = {
    200: GroupsCollection;
};

export type GetGroupResponse = GetGroupResponses[keyof GetGroupResponses];

export type PatchGroupData = {
    body: PatchGroupsRequest;
    path?: never;
    query?: never;
    url: '/chm/group';
};

export type PatchGroupResponses = {
    200: ResponseResult;
};

export type PatchGroupResponse = PatchGroupResponses[keyof PatchGroupResponses];

export type PostGroupData = {
    body: CreateGroupRequest;
    path?: never;
    query?: never;
    url: '/chm/group';
};

export type PostGroupResponses = {
    200: ResponseResult;
};

export type PostGroupResponse = PostGroupResponses[keyof PostGroupResponses];

export type PutGroupData = {
    body: PutGroupsRequest;
    path?: never;
    query?: never;
    url: '/chm/group';
};

export type PutGroupResponses = {
    200: ResponseResult;
};

export type PutGroupResponse = PutGroupResponses[keyof PutGroupResponses];

export type RevokeData = {
    body: RevokeRequest;
    path?: never;
    query?: never;
    url: '/chm/mCA/revoke';
};

export type RevokeErrors = {
    /**
     * 伺服器錯誤
     */
    500: ResponseResult;
};

export type RevokeError = RevokeErrors[keyof RevokeErrors];

export type RevokeResponses = {
    /**
     * 憑證吊銷成功
     */
    200: ResponseResult;
};

export type RevokeResponse = RevokeResponses[keyof RevokeResponses];

export type RevokedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/chm/mCA/revoked';
};

export type RevokedErrors = {
    /**
     * 伺服器錯誤
     */
    500: ResponseResult;
};

export type RevokedError = RevokedErrors[keyof RevokedErrors];

export type RevokedResponses = {
    /**
     * 取得吊銷憑證列表
     */
    200: GetRevokeds;
};

export type RevokedResponse = RevokedResponses[keyof RevokedResponses];

export type ValidData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/chm/mCA/valid';
};

export type ValidErrors = {
    /**
     * 伺服器錯誤
     */
    500: ResponseResult;
};

export type ValidError = ValidErrors[keyof ValidErrors];

export type ValidResponses = {
    /**
     * 取得有效憑證列表
     */
    200: GetValids;
};

export type ValidResponse = ValidResponses[keyof ValidResponses];

export type DeletePcData = {
    body: DeletePcRequest;
    path?: never;
    query?: never;
    url: '/chm/pc';
};

export type DeletePcErrors = {
    /**
     * 伺服器錯誤
     */
    500: ResponseResult;
};

export type DeletePcError = DeletePcErrors[keyof DeletePcErrors];

export type DeletePcResponses = {
    /**
     * 刪除特定主機
     */
    200: DeletePcResponse;
};

export type DeletePcResponse2 = DeletePcResponses[keyof DeletePcResponses];

export type AddPcData = {
    body: PcManagerRequest;
    path?: never;
    query?: never;
    url: '/chm/pc/add';
};

export type AddPcErrors = {
    /**
     * 伺服器錯誤
     */
    500: ResponseResult;
};

export type AddPcError = AddPcErrors[keyof AddPcErrors];

export type AddPcResponses = {
    /**
     * 添加成功
     */
    200: ResponseResult;
};

export type AddPcResponse = AddPcResponses[keyof AddPcResponses];

export type GetAllPcData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/chm/pc/all';
};

export type GetAllPcErrors = {
    /**
     * 伺服器錯誤
     */
    500: ResponseResult;
};

export type GetAllPcError = GetAllPcErrors[keyof GetAllPcErrors];

export type GetAllPcResponses = {
    /**
     * 取得所有主機
     */
    200: PcInformation;
};

export type GetAllPcResponse = GetAllPcResponses[keyof GetAllPcResponses];

export type RebootPcData = {
    body: UuidsRequest;
    path?: never;
    query?: never;
    url: '/chm/pc/reboot';
};

export type RebootPcErrors = {
    /**
     * 伺服器錯誤
     */
    500: ResponseResult;
};

export type RebootPcError = RebootPcErrors[keyof RebootPcErrors];

export type RebootPcResponses = {
    /**
     * 重啟特定主機
     */
    200: RebootPcResponse;
};

export type RebootPcResponse2 = RebootPcResponses[keyof RebootPcResponses];

export type ShutdownPcData = {
    body: UuidsRequest;
    path?: never;
    query?: never;
    url: '/chm/pc/shutdown';
};

export type ShutdownPcErrors = {
    /**
     * 伺服器錯誤
     */
    500: ResponseResult;
};

export type ShutdownPcError = ShutdownPcErrors[keyof ShutdownPcErrors];

export type ShutdownPcResponses = {
    /**
     * 關閉特定主機
     */
    200: ShutdownPcResponse;
};

export type ShutdownPcResponse2 = ShutdownPcResponses[keyof ShutdownPcResponses];

export type GetSpecificPcData = {
    body?: never;
    path?: never;
    query: {
        Uuid: Array<string>;
    };
    url: '/chm/pc/specific';
};

export type GetSpecificPcErrors = {
    /**
     * 伺服器錯誤
     */
    500: ResponseResult;
};

export type GetSpecificPcError = GetSpecificPcErrors[keyof GetSpecificPcErrors];

export type GetSpecificPcResponses = {
    /**
     * 取得特定主機
     */
    200: PcInformation;
};

export type GetSpecificPcResponse = GetSpecificPcResponses[keyof GetSpecificPcResponses];

export type DeletePcgroupData = {
    body: DeletePcGroupRequest;
    path?: never;
    query?: never;
    url: '/chm/pcgroup';
};

export type DeletePcgroupErrors = {
    /**
     * 伺服器錯誤
     */
    500: ResponseResult;
};

export type DeletePcgroupError = DeletePcgroupErrors[keyof DeletePcgroupErrors];

export type DeletePcgroupResponses = {
    /**
     * 刪除Group
     */
    200: ResponseResult;
};

export type DeletePcgroupResponse = DeletePcgroupResponses[keyof DeletePcgroupResponses];

export type GetPcgroupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/chm/pcgroup';
};

export type GetPcgroupErrors = {
    /**
     * 伺服器錯誤
     */
    500: ResponseResult;
};

export type GetPcgroupError = GetPcgroupErrors[keyof GetPcgroupErrors];

export type GetPcgroupResponses = {
    /**
     * 取得所有PC群組資訊
     */
    200: GetPcgroupResponseResult;
};

export type GetPcgroupResponse = GetPcgroupResponses[keyof GetPcgroupResponses];

export type PatchPcgroupData = {
    body: PatchPcgroupRequest;
    path?: never;
    query?: never;
    url: '/chm/pcgroup';
};

export type PatchPcgroupErrors = {
    /**
     * 伺服器錯誤
     */
    500: ResponseResult;
};

export type PatchPcgroupError = PatchPcgroupErrors[keyof PatchPcgroupErrors];

export type PatchPcgroupResponses = {
    /**
     * 更新整筆Group
     */
    200: ResponseResult;
};

export type PatchPcgroupResponse = PatchPcgroupResponses[keyof PatchPcgroupResponses];

export type PostPcgroupData = {
    body: PostPcgroupRequest;
    path?: never;
    query?: never;
    url: '/chm/pcgroup';
};

export type PostPcgroupErrors = {
    /**
     * 伺服器錯誤
     */
    500: ResponseResult;
};

export type PostPcgroupError = PostPcgroupErrors[keyof PostPcgroupErrors];

export type PostPcgroupResponses = {
    /**
     * 新增Group
     */
    200: ResponseResult;
};

export type PostPcgroupResponse = PostPcgroupResponses[keyof PostPcgroupResponses];

export type PutPcgroupData = {
    body: PutPcgroupRequest;
    path?: never;
    query?: never;
    url: '/chm/pcgroup';
};

export type PutPcgroupErrors = {
    /**
     * 伺服器錯誤
     */
    500: ResponseResult;
};

export type PutPcgroupError = PutPcgroupErrors[keyof PutPcgroupErrors];

export type PutPcgroupResponses = {
    /**
     * 更新整筆Group
     */
    200: ResponseResult;
};

export type PutPcgroupResponse = PutPcgroupResponses[keyof PutPcgroupResponses];

export type DeleteUserData = {
    body: DeleteUserRequest;
    path?: never;
    query?: never;
    url: '/chm/user';
};

export type DeleteUserResponses = {
    200: ResponseResult;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/chm/user';
};

export type GetUserResponses = {
    200: UsersCollection;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type PatchUserData = {
    body: PatchUsersRequest;
    path?: never;
    query?: never;
    url: '/chm/user';
};

export type PatchUserResponses = {
    200: ResponseResult;
};

export type PatchUserResponse = PatchUserResponses[keyof PatchUserResponses];

export type PostUserData = {
    body: CreateUserRequest;
    path?: never;
    query?: never;
    url: '/chm/user';
};

export type PostUserResponses = {
    200: ResponseResult;
};

export type PostUserResponse = PostUserResponses[keyof PostUserResponses];

export type PutUserData = {
    body: PutUsersRequest;
    path?: never;
    query?: never;
    url: '/chm/user';
};

export type PutUserResponses = {
    200: ResponseResult;
};

export type PutUserResponse = PutUserResponses[keyof PutUserResponses];

export type PostInfoGetData = {
    body: InfoGetRequest;
    path?: never;
    query?: never;
    url: '/info/get';
};

export type PostInfoGetErrors = {
    /**
     * 伺服器錯誤
     */
    500: ResponseResult;
};

export type PostInfoGetError = PostInfoGetErrors[keyof PostInfoGetErrors];

export type PostInfoGetResponses = {
    /**
     * 取得資訊
     */
    200: InfoGetResponse;
};

export type PostInfoGetResponse = PostInfoGetResponses[keyof PostInfoGetResponses];

export type GetInfoAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/info/getAll';
};

export type GetInfoAllErrors = {
    /**
     * 伺服器錯誤
     */
    500: ResponseResult;
};

export type GetInfoAllError = GetInfoAllErrors[keyof GetInfoAllErrors];

export type GetInfoAllResponses = {
    /**
     * 取得所有資訊
     */
    200: GetAllInfoResponse;
};

export type GetInfoAllResponse = GetInfoAllResponses[keyof GetInfoAllResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/login';
};

export type LoginErrors = {
    /**
     * 未授權
     */
    401: ResponseResult;
    /**
     * 禁止存取
     */
    403: ResponseResult;
    /**
     * 伺服器錯誤
     */
    500: ResponseResult;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * 登入成功
     */
    200: ResponseResult;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/login/me';
};

export type MeErrors = {
    /**
     * 未授權
     */
    401: ResponseResult;
    /**
     * 禁止存取
     */
    403: ResponseResult;
    /**
     * 伺服器錯誤
     */
    500: ResponseResult;
};

export type MeError = MeErrors[keyof MeErrors];

export type MeResponses = {
    /**
     * 登入資料取得成功
     */
    200: AuthUser;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/logout';
};

export type LogoutErrors = {
    /**
     * 伺服器錯誤
     */
    500: ResponseResult;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * 登出成功
     */
    200: ResponseResult;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetApacheAllData = {
    body?: never;
    path?: never;
    query: {
        Uuid: string;
    };
    url: '/server/apache';
};

export type GetApacheAllResponses = {
    200: ApacheResponse;
};

export type GetApacheAllResponse = GetApacheAllResponses[keyof GetApacheAllResponses];

export type ActionRestartData = {
    body: UuidRequest;
    path?: never;
    query?: never;
    url: '/server/apache/action/restart';
};

export type ActionRestartResponses = {
    200: ResponseResult;
};

export type ActionRestartResponse = ActionRestartResponses[keyof ActionRestartResponses];

export type ActionStartData = {
    body: UuidRequest;
    path?: never;
    query?: never;
    url: '/server/apache/action/start';
};

export type ActionStartResponses = {
    200: ResponseResult;
};

export type ActionStartResponse = ActionStartResponses[keyof ActionStartResponses];

export type ActionStopData = {
    body: UuidRequest;
    path?: never;
    query?: never;
    url: '/server/apache/action/stop';
};

export type ActionStopResponses = {
    200: ResponseResult;
};

export type ActionStopResponse = ActionStopResponses[keyof ActionStopResponses];

export type PostInstallData = {
    body: StallRequest;
    path?: never;
    query?: never;
    url: '/server/install';
};

export type PostInstallResponses = {
    200: ResponseResult;
};

export type PostInstallResponse = PostInstallResponses[keyof PostInstallResponses];

export type GetInstalledData = {
    body?: never;
    path?: never;
    query: {
        Server: string;
    };
    url: '/server/installed';
};

export type GetInstalledResponses = {
    200: StalledResponse;
};

export type GetInstalledResponse = GetInstalledResponses[keyof GetInstalledResponses];

export type GetNoinstallData = {
    body: StalledRequest;
    path: {
        Server: string;
    };
    query?: never;
    url: '/server/noinstall';
};

export type GetNoinstallResponses = {
    200: StalledResponse;
};

export type GetNoinstallResponse = GetNoinstallResponses[keyof GetNoinstallResponses];
